//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPSLab4 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class AutoShowInfo : global::System.Configuration.ApplicationSettingsBase {
        
        private static AutoShowInfo defaultInstance = ((AutoShowInfo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AutoShowInfo())));
        
        public static AutoShowInfo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoShowInfo {
            get {
                return ((bool)(this["autoShowInfo"]));
            }
            set {
                this["autoShowInfo"] = value;
            }
        }
    }
}
